# Generated by Django 3.2.4 on 2021-06-08 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkOutId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True)),
                ('amount', models.BigIntegerField(null=True)),
                ('MpesaReceipt', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('checkoutRequestId', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=3)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSuccess', models.BooleanField(default=False)),
                ('isPaidFor', models.BooleanField(default=False)),
                ('checkOutId', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='shop.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
